### ISSUE TITLE
403 ERROR at https://phys.libretexts.org/

### ISSUE THREAD

**Issue by mariohuq** [LibreTexts/Libretext#217]
I try to open https://phys.libretexts.org/
and get this error.

Full text error message:

```
403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: d79vqXdnHNU3QoUJZ3wd5Mvff_nF0JXuPUD667a-7otka3pgY0uPvQ==
```

**Comment by ymdahi** [comment]
Hello @mariohuq, are you still experiencing this issue. If so, can you please email me your IP address so we can attempt to track down the issue: yasin@libretexts.org.

**Comment by mariohuq** [comment]
@ymdahi yes it still exists. My IP - `31.134.187.26` (located in Russia, Saint-Petersburg)

**Comment by ethanaturner** [comment]
@mariohuq, some of our service providers are blocking traffic from the Russian Federation. I'm afraid we don't have an immediate fix for this.

You may be able to browse our catalog by visiting [LibreCommons](https://commons.libretexts.org), which will have options to download PDFs directly. If you still want to visit our library sites, you should be able to do so by using a VPN service.

I'm going to close this issue for now; please do [reach out to us](mailto:info@libretexts.org) if we can help otherwise!

**Comment by mariohuq** [comment]
@ethanaturner I see. Thank you for your response.
